bid_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views



urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
    path('signup/', views.signup, name="signup"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.Logout, name="logout"),
    path('add_product', views.Add_Product, name="add_product"),
    path('view_product', views.view_product, name="view_product"),
    path('delete_product/<int:pid>', views.delete_product, name="delete_product"),
    path('product_detail/<int:pid>', views.product_detail, name="product_detail"),
    path('make_participants/<int:pid>', views.make_participants, name="make_participants"),
    path('getbidhistory/<int:pid>', views.getbidhistory, name="getbidhistory"),
    path('startbidding/<int:pid>', views.startbidding, name="startbidding"),
    path('changelivetocomplete/<int:pid>', views.changelivetocomplete, name="changelivetocomplete"),
    path('changeupcomingtolive/<int:pid>', views.changeupcomingtolive, name="changeupcomingtolive"),
    path('delete_admin_product/<int:pid>', views.delete_admin_product, name="delete_admin_product"),
    path('delete_category/<int:pid>', views.delete_category, name="delete_category"),
    path('change_status/<int:pid>', views.change_status, name="change_status"),
    path('delete_sub_category/<int:pid>', views.delete_sub_category, name="delete_sub_category"),
    path('delete_user/<int:pid>', views.delete_user, name="delete_user"),
    path('delete_participant/<int:pid>', views.delete_participant, name="delete_participant"),
    path('profile/<int:pid>', views.profile, name="profile"),
    path('email_verify/<int:pid>', views.email_verify, name="email_verify"),
    path('generateotp/<int:pid>', views.generateotp, name="generateotp"),
    path('admin_product_detail/<int:pid>', views.admin_product_detail, name="admin_product_detail"),
    path('bidder_detail/<int:pid>', views.bidder_detail, name="bidder_detail"),
    path('seller_detail/<int:pid>', views.seller_detail, name="seller_detail"),
    path('edit_product/<int:pid>', views.edit_product, name="edit_product"),
    path('edit_profile', views.Edit_profile, name="edit_profile"),



    path('load-courses/', views.load_courses, name='ajax_load_courses'),
    path('meetwinners/', views.meetwinners, name='meetwinners'),
    path('all_product/', views.all_product, name='all_product'),


    path('admin-home/', views.admin_home, name='admin_home'),
    path('loginadmin', views.Admin_Login, name="loginadmin"),
    path('view_seller_user/', views.view_seller_user, name="view_seller_user"),
    path('view_buyer_user', views.view_buyer_user, name="view_buyer_user"),
    path('admin_view_product', views.Admin_product, name="admin_view_product"),
    path('add_categary', views.Add_Categary, name="add_categary"),
    path('view_categary', views.View_Categary, name="view_categary"),
    path('add_sub_categary', views.Add_Sub_Categary, name="add_sub_categary"),
    path('view_sub_category', views.View_Sub_Categary, name="view_sub_category"),
    path('view_participants', views.view_participants, name="view_participants"),
    path('view_winner', views.View_winner, name="view_winner"),
    path('change_password', views.Change_Password, name="change_password"),



    path('change_user_status/<int:pid>', views.change_user_status, name="change_user_status"),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('bid_app.urls')),
]

bid_app/models.py
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Member_fee(models.Model):
    fee = models.CharField(max_length=20,null=True)

    def __str__(self):
        return self.fee

class AuctionUser(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,null=True, blank=True)
    dob = models.DateField(null=True, blank=True)
    address = models.CharField(max_length=100,null=True, blank=True)
    contact = models.CharField(max_length=10,null=True, blank=True)
    image = models.FileField(null=True, blank=True)
    user_type = models.CharField(max_length=100,null=True, blank=True)
    status = models.CharField(max_length=100,null=True, blank=True, default="pending")
    #membership = models.ForeignKey(Member_fee,on_delete=models.CASCADE,null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    adhar_card = models.FileField(null=True, blank=True)
    pan_card = models.FileField(null=True, blank=True)
    bank_statement = models.FileField(null=True, blank=True)
    adhar_number = models.CharField(max_length=100,null=True, blank=True)
    pan_number = models.CharField(max_length=100,null=True, blank=True)
    account_number = models.CharField(max_length=100,null=True, blank=True)
    agree = models.BooleanField(null=True, blank=True)
    email_verification = models.BooleanField(null=True, blank=True)
    otp = models.CharField(max_length=100,null=True, blank=True)

    def __str__(self):
        return self.user.username

class Category(models.Model):
    name = models.CharField(max_length=100,null=True)
    def __str__(self):
        return self.name

class Sub_Category(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=100,null=True)
    def __str__(self):
        return self.name+" "+self.category.name


class Product(models.Model):
    status  = models.CharField(max_length=100,null=True, default='pending')
    bid_type  = models.CharField(max_length=100,null=True)
    payment_status  = models.CharField(max_length=100,null=True,default='pending')
    winner  = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='winner')
    user  = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='seller')
    name = models.CharField(max_length=100,null=True)
    min_price = models.IntegerField(null=True)
    final_price = models.IntegerField(null=True)
    interval_price = models.IntegerField(null=True)
    images = models.FileField(null=True)
    session = models.DateTimeField(null=True, blank=True)
    endsession = models.DateTimeField(null=True, blank=True, auto_now_add=True)
    category = models.ForeignKey(Sub_Category,on_delete=models.CASCADE,null=True)
    parameter = models.TextField(null=True, default="{}")
    description = models.TextField(null=True, blank=True)
    comment = models.TextField(null=True, blank=True)
    created = models.DateField(auto_now_add=True, null=True, blank=True)
    def __str__(self):
        return self.name

class Participants(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    new_price = models.IntegerField(null=True,default=0)
    product = models.ForeignKey(Product,on_delete=models.CASCADE,null=True)

    def __str__(self):
        return self.user.username+ " " + self.product.name

class ParticipantsHistory(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    new_price = models.IntegerField(null=True,default=0)
    product = models.ForeignKey(Product,on_delete=models.CASCADE,null=True)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.user.username+ " " + self.product.name


class Send_Feedback(models.Model):
    profile = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    message1 = models.TextField(null=True)
    date = models.CharField(max_length=30, null=True)

    def __str__(self):
        return self.profile.username

bid_app/views.py
from datetime import datetime, timezone
from email import message
from math import prod
from unicodedata import category
from django.shortcuts import render, redirect
from .models import *
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout
import random
import math
from django.conf import settings
from django.core.mail import EmailMessage
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.http import HttpResponse
from django.core.exceptions import ValidationError
from django.db import transaction


# Create your views here.
def send_bid_notification_email(winning_user, product):
    subject = "Congratulations! You participated in the bid"
    message = render_to_string('win_bid_email.html', {'product': product})
    plain_message = strip_tags(message)
    from_email = 'noreply@yourdomain.com'
    to = winning_user.email
    send_mail(subject, plain_message, from_email, [to], html_message=message)


def home(request):
    if request.user.is_authenticated:
        auctionuser = AuctionUser.objects.get(user=request.user)
        if auctionuser.status == "pending":
            messages.success(request, "Your verification is pending. complete your additional detail and email verification. if these are already completed then try login after sometime.We are working on your detail verification.Thanks!")
            return redirect('profile', request.user.id)
    upcoming_product = Product.objects.filter(status="upcoming")
    closed_product = Product.objects.filter(status="closed")
    live_product = Product.objects.filter(status="live")
    d = {'upcoming_product':upcoming_product, 'closed_product':closed_product, 'live_product':live_product}
    return render(request, 'home.html', d)

def about(request):
    return render(request, 'about.html')

def contact(request):
    return render(request, 'contact.html')

def signup(request):
    if request.method == 'POST':
        f = request.POST['fname']
        l = request.POST['lname']
        u = request.POST['uname']
        e = request.POST['email']
        p = request.POST['pwd']
        con = request.POST['contact']
        add = request.POST['add']
        d2 = request.POST['dob']
        reg = request.POST['reg']
        i = request.FILES['image']
        
        if not all([f, u, e, p, con, add, d2, reg, i]):
            messages.error(request, "All fields are required")
            return redirect('signup')
        
        if User.objects.filter(username=u).exists() or User.objects.filter(email=e).exists():
            messages.error(request, "Username or email already exists")
            return redirect('signup')
        
        try:
            with transaction.atomic():
                user = User.objects.create_user(email=e, username=u, password=p, first_name=f,last_name=l)
                mem = Member_fee.objects.get(fee="Unpaid")
                AuctionUser.objects.create(membership=mem,user=user,contact=con,address=add,dob=d2,image=i, user_type=reg)
                messages.success(request, "Registration Successfully")
                return redirect('home')
        except ValidationError as e:
            messages.error(request, "Validation error")
            
    return render(request, 'signup.html')

def Logout(request):
    logout(request)
    return redirect('home')

def login_user(request):
    if request.method == "POST":
        u = request.POST['uname']
        p = request.POST['pwd']
        user = authenticate(username=u, password=p)
        sign = ""
        if user and not user.is_staff:
            login(request, user)
            messages.success(request, "Logged in Successfully")
            return redirect('home')
        else:
            messages.success(request, "Invalid credential")
    return render(request, 'login.html')


def Add_Product(request):
    if not request.user.is_authenticated:
        return redirect('login')
    if request.user.is_authenticated:
        auctionuser = AuctionUser.objects.get(user=request.user)
        if auctionuser.status == "pending":
            messages.success(request, "Your verification is pending. complete your additional detail and email verification. if these are already completed then try login after sometime.We are working on your detail verification.Thanks!")
            return redirect('profile', request.user.id)
    cat = Category.objects.all()
    scat = Sub_Category.objects.all()
    sell = AuctionUser.objects.get(user=request.user)
    if request.method == "POST":
        c = request.POST['cat']
        s = request.POST['scat']
        p = request.POST['p_name']
        pr = request.POST['price']
        im = request.FILES['image']
        start = request.POST['start']
        end = request.POST['interval_price']
        desc = request.POST['desc']
        bid_type = request.POST['bid_type']
        numberofparts = request.POST['numberofparts']
        print(numberofparts)
        dict_val = {}
        lst = []
        for i in range(int(numberofparts)):
            print(i)
            
            parts_name = request.POST.get(f'parts_name-{i}', None)
            parts_image = request.FILES.get(f'parts_image-{i}', None)
            
            myli = [parts_name, parts_image]
            lst.append(myli)
        res_dct = {i[0]: i[1] for i in lst}
        sub = Sub_Category.objects.get(id=s)
        pro1=Product.objects.create(description=desc, bid_type=bid_type, status="pending",session=start, interval_price=end, category=sub, name=p, min_price=pr, final_price=pr, images=im, parameter=res_dct, user=request.user)
        messages.success(request, "Product added successfully.")
        return redirect('view_product')
    d = {'cat': cat,'scat':scat}
    return render(request, 'add_product.html', d)


def edit_product(request, pid):
    if not request.user.is_authenticated:
        return redirect('login_admin')
    
    if request.user.is_authenticated:
        auctionuser = AuctionUser.objects.get(user=request.user)
        if auctionuser.status == "pending":
            messages.success(request, "Your verification is pending. complete your additional detail and email verification. if these are already completed then try login after sometime.We are working on your detail verification.Thanks!")
            return redirect('profile', request.user.id)
    data = Product.objects.get(id=pid)
    cat = Category.objects.all()
    scat = Sub_Category.objects.all()
    if request.method=="POST":
        c = request.POST['cat']
        s = request.POST['scat']
        p = request.POST['p_name']
        pr = request.POST['price']
        start = request.POST['start']
        end = request.POST['interval_price']
        desc = request.POST['desc']
        bid_type = request.POST['bid_type']
        try:
            i = request.FILES['image']
            data.images = i
            data.save()
        except:
            pass
        d = request.POST['desc']
        numberofparts = request.POST.get('numberofparts')
        if not numberofparts:
            numberofparts = 0
        edit_len = len(eval(data.parameter))

        lst2 = []
        for i in range(1, int(edit_len)+1):
            parts_name = request.POST['edit_parts_name-'+str(i)]
            parts_image = request.POST['edit_parts_image-'+str(i)]
            myli = [parts_name, parts_image]
            lst2.append(myli)
        dict_val = {i[0]: i[1] for i in lst2}

        lst = []
        for i in range(int(numberofparts)):
            parts_name = request.POST['parts_name-'+str(i)]
            parts_image = request.POST['parts_image-'+str(i)]
            myli = [parts_name, parts_image]
            lst.append(myli)
        res_dct = {i[0]: i[1] for i in lst}
        dict_val.update(res_dct)
        sub = Sub_Category.objects.get(id=s)
        Product.objects.filter(id=pid).update(description=desc, bid_type=bid_type,session=start, interval_price=end, category=sub, name=p, min_price=pr, final_price=pr, parameter=dict_val, user=request.user)
        messages.success(request, "Product Updated")
        return redirect('view_product')
    d = {'cat': cat,'scat':scat, 'data':data}
    return render(request, 'edit_product.html', d)




def load_courses(request):
    if not request.user.is_authenticated:
        return redirect('login')
    programming_id = request.GET.get('programming')
    courses = Sub_Category.objects.filter(category_id=programming_id).order_by('name')
    return render(request, 'courses_dropdown_list_options.html', {'courses': courses})


def view_product(request):
    if not request.user.is_authenticated:
        return redirect('login')
    if request.user.is_authenticated:
        auctionuser = AuctionUser.objects.get(user=request.user)
        if auctionuser.status == "pending":
            messages.success(request, "Your verification is pending. complete your additional detail and email verification. if these are already completed then try login after sometime.We are working on your detail verification.Thanks!")
            return redirect('profile', request.user.id)
    product = Product.objects.filter(user=request.user)
    return render(request, 'view_product.html', {'product': product})


def delete_product(request,pid):
    if not request.user.is_authenticated:
        return redirect('login')
    pro = Product.objects.get(id=pid)
    pro.delete()
    messages.success(request, "Deleted Successfully")
    return redirect('view_product')

def product_detail(request, pid):
    if not request.user.is_authenticated:
        return redirect('login')
    if request.user.is_authenticated:
        auctionuser = AuctionUser.objects.get(user=request.user)
        if auctionuser.status == "pending":

bid_app/templates/administration/add_category.html
{% extends 'administration/index.html' %}
{% load static %}
{% block body %}

<div class="main-panel">
    <div class="content-wrapper">
      <div class="page-header">
        <h3 class="page-title"> Add category </h3>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">add-category</li>
          </ol>
        </nav>
      </div>
      <div class="row">
        <div class="col-12 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Add category</h4>
              <form class="forms-sample" action="" method="post">
                  {% csrf_token %}
                <div class="form-group">
                  <label for="exampleInputName1"> cactegory</label>
                  <input type="text" class="form-control" id="exampleInputName1" name="cat" placeholder="Enter Category">
                </div>
                
                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                <button class="btn btn-dark">Cancel</button>
              </form>
            </div>
          </div>
        </div>
        
        
        
        
        
        
        
        
      </div>
    </div>
    {% if error %}
    <script>
        alert('One New Category Added Successfully');
    </script>
    {% endif %}
{% endblock %}

bid_app/templates/administration/add_sub_categary.html
{% extends 'administration/index.html' %}
{% load static %}
{% block body %}

<div class="main-panel">
    <div class="content-wrapper">
      <div class="page-header">
        <h3 class="page-title"> Add Sub category </h3>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">sub-category</li>
          </ol>
        </nav>
      </div>
      <div class="row">
        <div class="col-12 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Add Sub category</h4>
              <form class="forms-sample" action="" method="post">
                  {% csrf_token %}

                  <div class="form-group">
                    <label for="exampleInputName1">Sub cactegory</label>
                    <select class="form-control" id="exampleInputName1" name="cat" required>
                        <option>Select Category</option>
                        {% for i in cat  %}
                            <option value="{{i.id}}">{{i.name}}</option>
                        {% endfor %}
                    </select>
                  </div>


                <div class="form-group">
                  <label for="exampleInputName1">Sub cactegory</label>
                  <input type="text" class="form-control" id="exampleInputName1" name="subcat" required placeholder="Enter Sub Category">
                </div>
                
                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                <button class="btn btn-dark">Cancel</button>
              </form>
            </div>
          </div>
        </div>
        
        
        
        
        
        
        
        
      </div>
    </div>
    {% if error %}
    <script>
        alert('One New Category Added Successfully');
    </script>
    {% endif %}
{% endblock %}

bid_app/templates/administration/status.html
{% extends 'administration/index.html' %}
{% load static %}
{% block body %}

<div class="main-panel">
    <div class="content-wrapper">
      <div class="page-header">
        <h3 class="page-title"> Change Status </h3>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Change Status</li>
          </ol>
        </nav>
      </div>
      <div class="row">
        <div class="col-12 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Change Status</h4>
              <form class="forms-sample" action="" method="post">
                  {% csrf_token %}
                  <div class="form-group col-md-12">
                    <label for="exampleInputEmail1">Booking Id</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="book" value="{{book.booking_id}}">
                  </div>
                  <div class="form-group col-md-12">
                      <label for="inputState">Status</label>
                      <select id="inputState" class="form-control" name="status">
                          {% for i in stat %}
                        <option value="{{i.name}}">{{i.name}}</option>
                          {% endfor %}
                      </select>
                    </div>
                
                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                <button class="btn btn-dark">Cancel</button>
              </form>
            </div>
          </div>
        </div>
        
        
        
        
        
        
        
        
      </div>
    </div>
{% endblock %}

bid_app/templates/administration/view_participants.html
{% extends 'administration/index.html' %}
{% load static %}
{% block body %}

<link rel = stylesheet href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap.min.css">

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>

<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js" defer></script>

<style>

    #example_length{
      text-align:left;
      margin-bottom:2%;
    }
  
    .dataTables_length{
      text-align:left;
    }
  
    .paginate_button{
        border:1px solid gray;
        padding:6px;
        cursor: pointer;
        color:white;
        background-color:green;
        margin:1px;
    }
  
    .dataTables_info{
      display:none;
    }
  
  </style>

<div class="main-panel">
    <div class="content-wrapper">
      <div class="page-header">
        <h3 class="page-title"> Seller participants reports </h3>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">participants-user-report</li>
          </ol>
        </nav>
      </div>
      <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">View Participants</h4>
              
              </p>
              <div class="table-responsive">
                <table class="table table-striped" id="example">
                  <thead>
                    <tr>
                        <th>Image</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                          <th>Contact</th>
                        <th>Email Id</th>
                        <th>Product</th>
                        <th>Start</th>
                        <th>Delete</th>
                      </tr>
                      </thead>
                       <tbody>
                    
                        {% for i in pro %}
                      <tr>
                    
                        <td><img src="{{i.user.auctionuser_set.all.0.image.url}}"></td>
                        <td>{{i.user.first_name}}</td>
                        <td>{{i.user.last_name}}</td>
                          <td>{{i.user.auctionuser_set.all.0.contact}}</td>
                          <td>{{i.user.email}}</td>
                          <td>{{i.product.name}}</td>
                          <td>{{i.product.session}}</td>
                        {% comment %} <td><a href="{% url 'change_user_status' i.id %}" onclick="return confirm('Are you sure to change status?')"><button class="btn btn-info">{{i.status}}</button></a></td> {% endcomment %}
                        <td><a href="{% url 'delete_participant' i.id %}" onclick="return confirm('Are you sure?')"><button class="btn btn-danger">delete</button></a></td>
                      </tr>
                        {% empty %}
                    <tr>
                      <td>Data Not Found</td>
                    </tr>
                        {% endfor %}
                        </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


    <script>
        $(document).ready(function() {
            //Only needed for the filename of export files.
            //Normally set in the title tag of your page.
            document.title='Simple DataTable';
            // DataTable initialisation
            $('#example').DataTable(
                {
                    "dom": '<"dt-buttons"Bf><"clear">lirtp',
                    "paging": true,
                    "autoWidth": true,
                    "buttons": [
                        'colvis',
                        'copyHtml5',
                'csvHtml5',
                        'excelHtml5',
                'pdfHtml5',
                        'print'
                    ]
                }
            );
        });
        </script>

{% endblock %}

bid_app/templates/administration/view_winner.html
{% extends 'administration/index.html' %}
{% load static %}
{% block body %}

<link rel = stylesheet href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap.min.css">

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>

<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js" defer></script>

<style>

    #example_length{
      text-align:left;
      margin-bottom:2%;
    }
  
    .dataTables_length{
      text-align:left;
    }
  
    .paginate_button{
        border:1px solid gray;
        padding:6px;
        cursor: pointer;
        color:white;
        background-color:green;
        margin:1px;
    }
  
    .dataTables_info{
      display:none;
    }
  
  </style>

<div class="main-panel">
    <div class="content-wrapper">
      <div class="page-header">
        <h3 class="page-title"> Winner reports </h3>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">winner-user-report</li>
          </ol>
        </nav>
      </div>
      <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">View Winner</h4>
              
              </p>
              <div class="table-responsive">
                <table class="table table-striped" id="example">
                  <thead>
                    <tr>
                        <th>Image</th>
                        <th>winner Name</th>
                        <th>Winner Contact</th>
                        <th>Seller Name</th>
                        <th>Seller Contact</th>
                        <th>Booking Price</th>
                        <th>Product</th>
                        <th>Start</th>
                        <th>Payment Status</th>
                        <th>Action</th>
                      </tr>
                      </thead>
                       <tbody>
                    
                        {% for i in pro %}
                      <tr>
                    
                        <td><img src="{{i.winner.auctionuser_set.all.0.image.url}}"></td>
                        <td>{{i.winner.first_name}} {{i.winner.last_name}}</td>
                        <td>{{i.user.first_name}} {{i.user.last_name}}</td>
                          <td>{{i.winner.auctionuser_set.all.0.contact}}</td>
                          <td>{{i.user.auctionuser_set.all.0.contact}}</td>
                          <td>{{i.final_price}}</td>
                          <td>{{i.name}}</td>
                          <td>{{i.session}}</td>
                          <td>{{i.payment_status}}</td>
                        <td><a href="{% url 'admin_product_detail' i.id %}"><button class="btn btn-info">Detail</button></a></td>
                        
                      </tr>
                        {% empty %}
                    <tr>
                      <td>Data Not Found</td>
                    </tr>
                        {% endfor %}
                        </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


    <script>
        $(document).ready(function() {
            //Only needed for the filename of export files.
            //Normally set in the title tag of your page.
            document.title='Simple DataTable';
            // DataTable initialisation
            $('#example').DataTable(
                {
                    "dom": '<"dt-buttons"Bf><"clear">lirtp',
                    "paging": true,
                    "autoWidth": true,
                    "buttons": [
                        'colvis',
                        'copyHtml5',
                'csvHtml5',
                        'excelHtml5',
                'pdfHtml5',
                        'print'
                    ]
                }
            );
        });
        </script>

{% endblock %}